INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('God of War', 9.8, 2018, 'Action-Adventure', 'PlayStation 4', 'https://www.godofwar.com/static/share/share_02.jpg', 'God of War is an epic action-adventure game that takes players on a journey through Norse mythology, as they play as Kratos and his son Atreus to fulfill their quest.', 'God of War is a critically acclaimed game that won multiple Game of the Year awards in 2018. It features a stunning open world full of mythical creatures, challenging puzzles, and an emotionally driven story that explores the relationship between Kratos and Atreus.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Horizon Zero Dawn', 9.3, 2017, 'Action-Adventure', 'PlayStation 4, PC', 'https://cdn-products.eneba.com/resized-products/aauFQ2yM9Xfj3At3-K0vLWrWQz8ExIBNlLFN3qIvjc0_390x400_1x-0.jpeg', 'Horizon Zero Dawn is a post-apocalyptic open-world game that takes place in a world where robotic creatures roam the land, and players play as Aloy, a skilled hunter who sets out to uncover the mysteries of her past.', 'Horizon Zero Dawn is a game that received critical acclaim for its stunning graphics, engaging story, and unique setting. It offers a vast open world full of different environments to explore, a variety of enemies to fight, and an exciting story that keeps players engaged from start to finish.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 9.7, 2015, 'Action-Adventure, RPG', 'PC, PlayStation 4, Xbox One, Nintendo Switch', 'https://images-na.ssl-images-amazon.com/images/I/81z2qlE8WAL._SL1500_.jpg', 'The Witcher 3: Wild Hunt is an epic action RPG that takes place in a vast open world full of monsters, magic, and political intrigue. Players play as Geralt of Rivia, a monster hunter, and set out to find his adopted daughter.', 'The Witcher 3: Wild Hunt is a game that is widely regarded as one of the best games ever made. It offers a deep and engaging story, a vast open world full of interesting characters and side quests, and an innovative combat system that allows players to customize Geralt abilities and playstyle.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Bloodborne', 9.4, 2015, 'Action RPG', 'PlayStation 4', 'https://www.gamerevolution.com/assets/uploads/2015/03/bloodborne-review-900x506.jpg', 'Bloodborne is a visceral and challenging game set in a gothic-inspired world filled with eldritch horrors and grotesque monsters.', 'Players must explore the city of Yharnam, uncovering its secrets and fighting for survival in a brutal and unforgiving world.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Dark Souls III', 9.5, 2016, 'Action RPG', 'PC, PlayStation 4, Xbox One', 'https://www.gamerevolution.com/assets/uploads/2016/03/dark-souls-3-review-900x506.jpg', 'Dark Souls III is a challenging and atmospheric game that takes players on a journey through a dying world filled with formidable enemies and breathtaking landscapes.', 'Players must explore the Kingdom of Lothric, uncovering its mysteries and fighting for survival in a world on the brink of collapse.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Red Dead Redemption 2', 9.8, 2018, 'Action-Adventure', 'PlayStation 4, Xbox One, PC, Stadia', 'https://i.redd.it/7h2pg9e3z3q31.jpg', 'Red Dead Redemption 2 is an epic open-world game that takes place in the Wild West. Players play as Arthur Morgan, a member of the Van der Linde gang, and set out to survive in a world filled with outlaws, lawmen, and other dangers.', 'Red Dead Redemption 2 is a game that received critical acclaim for its stunning graphics, immersive gameplay, and compelling story. It offers a vast open world full of different environments to explore, a variety of enemies to fight, and an exciting story that keeps players engaged from start to finish.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Assassin’s Creed Valhalla', 8.9, 2020, 'Action-Adventure, RPG', 'PlayStation 5, PlayStation 4, Xbox Series X/S, Xbox One, PC, Stadia', 'https://www.rockpapershotgun.com/wp-content/uploads/2020/05/AC-V-Header-900x500.jpg', 'Assassin’s Creed Valhalla is an open-world game that takes place in the Viking Age. Players play as Eivor, a Viking warrior, and set out to build a new home in England and establish alliances with the locals, all while fighting against rival clans and the Templar Order.', 'Assassin’s Creed Valhalla is a game that received critical acclaim for its immersive gameplay, stunning visuals, and interesting story. It offers a vast open world full of different environments to explore, a variety of enemies to fight, and an exciting story that keeps players engaged from start to finish.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Last of Us Part II', 9.0, 2020, 'Action-Adventure', 'PlayStation 4', 'https://cdn-products.eneba.com/resized-products/i9ZpN--fNl-mwElG0eSTOJyUhPLCQFQ0y0IlJvzGL9Y_390x400_1x-0.jpeg', 'The Last of Us Part II is an emotionally charged game that takes place in a post-apocalyptic world. Players play as Ellie, a young woman who sets out on a journey of revenge after a tragic event.', 'The Last of Us Part II is a game that received critical acclaim for its gripping story, stunning visuals, and engaging gameplay. It offers a world full of different environments to explore, a variety of enemies to fight, and an emotional story that keeps players engaged from start to finish.');

INSERT INTO tb_game_list (name) VALUES ('Adventure & RPG');
INSERT INTO tb_game_list (name) VALUES ('Platform Games');

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 3, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 5, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 6, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 7, 4);

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 2, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 4, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 8, 2);